# Generated by Django 3.2 on 2022-01-26 18:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='teachers',
            fields=[
                ('teacher_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('phone_number', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('address', models.CharField(max_length=100)),
                ('ratings', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=3, validators=[django.core.validators.MaxValueValidator(5.0), django.core.validators.MinValueValidator(0.1)])),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('class_specialisation', models.CharField(max_length=20, null=True)),
                ('occupation', models.CharField(max_length=50, null=True)),
                ('experience', models.IntegerField(default=0)),
                ('subject', models.CharField(default='None', max_length=100)),
            ],
        ),
    ]
