# Generated by Django 4.0.1 on 2022-01-14 16:55

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teachers', '0002_alter_teachers_ratings'),
    ]

    operations = [
        migrations.CreateModel(
            name='courses',
            fields=[
                ('course_id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course_name', models.CharField(max_length=50)),
                ('course_type', models.CharField(max_length=50)),
                ('course_description', models.TextField(max_length=500)),
                ('course_class_strength', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(300)])),
                ('course_instructor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachers.teachers')),
            ],
        ),
    ]
