# Generated by Django 3.2 on 2022-01-26 18:59

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teachers', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='courses',
            fields=[
                ('course_id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course_name', models.CharField(max_length=50)),
                ('course_type', models.CharField(max_length=50)),
                ('course_description', models.TextField(max_length=500)),
                ('course_class_strength', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(300)])),
                ('course_meet_link', models.CharField(max_length=150, null=True)),
                ('course_instructor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachers.teachers')),
            ],
        ),
        migrations.CreateModel(
            name='student_teachers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_instructor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachers.teachers')),
                ('registered_course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.courses')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student')),
            ],
        ),
        migrations.CreateModel(
            name='course_requests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approval_status', models.CharField(max_length=50)),
                ('course_instructor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachers.teachers')),
                ('requested_course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.courses')),
                ('requested_student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student')),
            ],
        ),
    ]
