
# Generated by Django 3.2 on 2022-01-16 04:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_alter_teachers_ratings'),
        ('students', '0001_initial'),
        ('courses', '0002_course_requests'),
    ]

    operations = [
        migrations.CreateModel(
            name='student_teachers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_instructor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachers.teachers')),
                ('registered_course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.courses')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student')),
            ],
        ),
    ]
